[package]
name = "vertin"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

[[bin]]
name = "mlaa"
path = "src/bin/mlaa.rs"
